[pytest]
# Root of the project, pytest looks for tests starting from this location
testpaths = tests

# Naming of test files and functions (default values, explicitly for clarity)
python_files  = test_*.py
python_classes = Test*
python_functions = test_*

# addopts = -v --tb=short